# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:
- {name: 'Sobre mí', path: 'menu', url: 'about.html'}
# - {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contacto', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/jgonzalezab'}
- {icon: 'twitter', link: 'https://twitter.com/jogonzab'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'envelope', link: 'mailto:jose.gonz.abad@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Posts Recientes'
  previous_page: 'Posts Antiguos'

sharing_button_prompt: '¿Te ha gustado? Compártelo'

related_posts: 'Quizás también te guste:'

post_date_prefix: 'Written on'
